package com.pojo;

// Generated 15 Jun, 2021 6:45:23 PM by Hibernate Tools 3.4.0.CR1

/**
 * Contactus generated by hbm2java
 */
public class Contactus implements java.io.Serializable {

	private Integer contid;
	private String fname;
	private String lname;
	private String email;
	private String message;

	public Contactus() {
	}

	public Contactus(String fname, String lname, String email, String message) {
		this.fname = fname;
		this.lname = lname;
		this.email = email;
		this.message = message;
	}

	public Integer getContid() {
		return this.contid;
	}

	public void setContid(Integer contid) {
		this.contid = contid;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

}
